### ISSUE TITLE
[Sonido] Samples

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#10]
Buscar samples de sonido libres o con lo licencia que nos permita utilizarlos.

**Comment by juanmanuelcarrera** [comment]
### Links con canciones libres:

- https://www.jamendo.com/
- http://www.mobygratis.com/catalog

**Comment by MicTome** [comment]
## **Links con canciones libres:**

- http://www.freesfx.co.uk/soundeffects/instruments

- http://www.audiomicro.com/

- https://blog.landr.com/6-free-sample-packs-every-producer-needs/

- https://www.musicradar.com/news/tech/free-music-samples-download-loops-hits-and-multis-627820

**Comment by juanmanuelcarrera** [comment]
Muevo los samples a una sección de la Wiki https://github.com/juanmanuelcarrera/feelmusic/wiki/Referencias
