### ISSUE TITLE
[Sonido] Revisar samples Android

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#19]
Revisar que funcionan correctamente los sonidos después de haber hecho una modificación en iOS para que carguen correctamente los samples.

**Comment by alosarjos** [comment]
¿A que te refieres con "haber hecho una modificación en iOS"?

**Comment by juanmanuelcarrera** [comment]
En la vista de Sound, si te fijas en el commit de @MicTome, cargaba los sonidos con esta línea `new Sound( require('./../samples/sample.mp3'), Sound.MAIN_BUNDLE);`, en iOS no funcionaba y he tenido que ajustarlo para que funcione con el `require`, entonces falta probarlo en Android.

**Comment by juanmanuelcarrera** [comment]
En este issue explica el problema zmxv/react-native-sound#160

**Comment by alosarjos** [comment]
En el emulador de Android funciona sin problemas según esta ahora en master

**Comment by MicTome** [comment]
En el smartphone con Android también funcionan
