### ISSUE TITLE
Añadir integración continua

### ISSUE THREAD

**Issue by alosarjos** [juanmanuelcarrera/feelmusic#20]
Deberíamos tener un sistema de integración continua, permitiría automáticamente saber si un branch compila antes de hacer un mere (y hacer tests en caso de que apetezcan).

Tengo el fichero de configuración listo, pero antes @juanmanuelcarrera tiene que ir a Travis-CI, iniciar sesión con su cuenta de GitHub y activar el CI para este proyecto. Una vez este hecho, puedo hacer un commit con el archivo de configuración para que empiece a funcionar.

PD: A pesar de estar como contribuidor, no puedo dar de alta yo el proyecto en Travis

**Comment by juanmanuelcarrera** [comment]
@alosarjos ya está dada de alta en TravisCI, añadiendo el `.travis.yml` y haciendo un `push` te debería lanzar el webhook y hacer el build

**Comment by alosarjos** [comment]
Añadido y funcionando, si quieres puedes mirar de meterlo como requisito para pula repuestos el que tenga que pasar la integración continua. De paso he añadido el build status al README

**Comment by juanmanuelcarrera** [comment]
Faltaría añadir la parte del build & test de iOS. Issue #21

**Comment by alosarjos** [comment]
Podemos cerrar este ahora que #21 esta solucionado.
