### ISSUE TITLE
[Compass] Compass doesn't work

### ISSUE THREAD

**Issue by MicTome** [juanmanuelcarrera/feelmusic#23]
Después de hacer el prototipo y juntarlo todo, el Compass no funciona en el mismo.
Tampoco funciona en el Compass original y no se por qué, dado que el archivo es exactamente igual.
Las pruebas están hechas en el movil.

Puede ser por algo que parece que he cambiado del npm, el ^version, aunque según he visto el commit anterior está igual.

**Comment by juanmanuelcarrera** [comment]
Estoy actualizando el compass para incluir Redux, subo la actualización y podéis probar para ver si funciona correctamente

**Comment by alosarjos** [comment]
Me funciona sin problemas la brújula en el Nexus (Android). Si no hay problemas en iOS diría de cerrar este problema

**Comment by juanmanuelcarrera** [comment]
En iOS funciona correctamente, cierro el issue
