### ISSUE TITLE
[Sonidos][Gestos] Mapear gestos para reproducir los sonidos

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#28]
Mapear gestos para reproducir sonidos de diferente forma, por ejemplo, gesto hacia la izquierda, reproducir en bucle cada segundo...

**Comment by MicTome** [comment]
Se han mapeado dos gestos nuevos a parte del original de inclinar el movil hacia adelante para que suene.

El primero permite reproducir en blucle el sonido indicado, para ello hay que inclinar el movil como con el anterior y una vez en horizontal, inclinarlo hacia la izquierda.

El otro es lo mismo pero inclinando hacia la derecha, lo que reproduce el sonido una vez a mitad de volumen.
