### ISSUE TITLE
[UI] Mockups para la interfaz final

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#33]
Crear mockups para plantear y decidir las líneas generales del diseño final de la aplicación

**Comment by alosarjos** [comment]
![captura de pantalla de 2018-05-13 17-09-07](https://user-images.githubusercontent.com/29999427/39968618-638a542a-56d0-11e8-9798-6eb0b1da9578.png)

Esto podría ser la vista en base a la idea de pestañas comentada en #37

**Comment by juanmanuelcarrera** [comment]
Me parece bien el mapear cuatro sonidos por pestaña, y cuatro pestañas son 16 sonidos que están muy bien

**Comment by MicTome** [comment]
Me gusta este diseño, ya está preparado para tener 16 sonidos en caso de usar este.

**Comment by alosarjos** [comment]
Con el diseño final ya hecho, cierro por aquí.
