### ISSUE TITLE
[AR] Pruebas de concepto para incluir realidad aumentada

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#35]
Prueba de concepto para valorar la inclusión de realidad aumentada para poder seleccionar el instrumento o sonido que emitirá el sonido.

**Comment by alosarjos** [comment]
Haciendo pruebas tiene pinta de que vamos a necesitar un servidor que se encarge del procesamiento de AR salvo que lo hagamos con ARKit. Pero no tengo un iPhone para hacer pruebas y no me parece adecuado para un proyecto multiplataforma. Sigo mirando alternativas a ver...

**Comment by juanmanuelcarrera** [comment]
Vamos a dejar esto de momento y nos centramos en el resto de funcionalidad

**Comment by juanmanuelcarrera** [comment]
Desestimado
