### ISSUE TITLE
[Sonidos] Varias ruedas de sonidos

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#37]
Valorar si incluir varias ruedas de sonidos, para tener disponibles más de 4/6 sonidos de forma simultánea.

**Comment by juanmanuelcarrera** [comment]
¿@alosarjos @MicTome @alosarjos metemos varias ruedas, cada una con sus sonidos, para poder meter más de 4/6 sonidos? Tendríamos un scroll lateral de ruedas que lo cambiamos con un swip o con un selector o algo

**Comment by juanmanuelcarrera** [comment]
### https://github.com/aksonov/react-native-tabs

![react-native-tabs](https://cloud.githubusercontent.com/assets/1321329/10188030/adf5532c-675c-11e5-8447-227ec38fa24f.gif)

**Comment by juanmanuelcarrera** [comment]
Esta tine mejor pinta: https://github.com/react-native-community/react-native-tab-view

**Comment by alosarjos** [comment]
Esta implementado y funciona, aunque supone un gran consumo de recursos. En cualquier caso cerraría el issue.
