### ISSUE TITLE
Master no funciona en Android

### ISSUE THREAD

**Issue by alosarjos** [juanmanuelcarrera/feelmusic#38]
El branch Master no funciona en Android enseñando la pantalla que pongo a continuación

![screenshot_20180513-173913](https://user-images.githubusercontent.com/29999427/39968940-4f3dbe44-56d5-11e8-9a57-885ab7b1fa32.png)

En algún commit los archivos Java de Android duplicaron la inclusión de librerías. El último commit en develop tan solo soluciona esto. Si no hay nada más extraño entre develop y master (Que creo que no) propongo hacer ya mismo un pull request

**Comment by juanmanuelcarrera** [comment]
@alosarjos perfecto, pues ya tenemos listo el pull request. Se quedaría algo residual del prototipo, vamos a trabajar con develop y con las ramas de features

**Comment by juanmanuelcarrera** [comment]
@alosarjos si funciona correctamente cerramos el issue
