### ISSUE TITLE
[Sonidos] Adicción de nuevos gestos

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#41]
Añadir nuevos gestos para la reproducción de sonidos

**Comment by MicTome** [comment]
Se han añadido los siguientes gestos cuando el teléfono está en horizontal:

- Inclinar hacia la izquierda: reproduce el sonido en bucle. Para parar la reproducción se tiene que inclinar el móvil dos veces más hacia el mismo lado.

- Inclinar hacia la derecha: se reproduce el sonido una vez.
