### ISSUE TITLE
[Sonido] Formatos

### ISSUE THREAD

**Issue by juanmanuelcarrera** [juanmanuelcarrera/feelmusic#9]
Buscar formatos de sonido y evaluar cuál es la mejor opción.

**Comment by MicTome** [comment]
De momento de los formatos admitidos por react native, sólo mp3 y wav funcionan en Android

**Comment by juanmanuelcarrera** [comment]
Abro hilo en la Wiki para comentar y detallar los formatos disponibles y por revisar
